name: Build and Push Docker Images

on:
  push:
    branches: [ main, master, develop ]

env:
  REGISTRY: cr.yandex/crp57fpjmeiqsivdd228
  IMAGE_TAG: ${{ github.ref_name }}-${{ github.sha }}

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 30  # Увеличиваем общий таймаут

    strategy:
      matrix:
        service: [
          { name: "adservice", path: "adservice" },
          { name: "cartservice", path: "cartservice/src" },
          { name: "currencyservice", path: "currencyservice" },
          { name: "emailservice", path: "emailservice" },
          { name: "frontend", path: "frontend" },
          { name: "paymentservice", path: "paymentservice" },
          { name: "productcatalogservice", path: "productcatalogservice" },
          { name: "recommendationservice", path: "recommendationservice" },
          { name: "shippingservice", path: "shippingservice" },
          { name: "shoppingassistantservice", path: "shoppingassistantservice" }
        ]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          driver-opts: |
            image=moby/buildkit:buildx-stable-1
            network=host
          buildkitd-flags: --debug
          install: true

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: ./${{ matrix.service.path }}
          push: true
          tags: |
            ${{ env.REGISTRY }}/${{ matrix.service.name }}:${{ env.IMAGE_TAG }}
            ${{ env.REGISTRY }}/${{ matrix.service.name }}:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max